<a href="https://colab.research.google.com/github/Megha77/Expertise-fullstack-GenAI-Agentic-AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Array Creation Functions

In [2]:
import numpy as np

In [3]:
# Create an array from a list
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# Create an array with evenly spaced values
b=np.arange(0,10,3)
b

array([0, 3, 6, 9])

In [11]:
# Create an array filled with zeros
c=np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Create an array filled with zeros
d=np.zeros((2,3),dtype=int)
#d=np.zeros((2,4),dtype=int)
d

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
# Create an array filled with ones
e=np.ones((3,4))
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# Create an identity matrix
f=np.eye(4) # 4x4 identity matrix
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# 2. Array Manipulation Functions

In [24]:
# Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
reshaped

array([[1, 2, 3]])

In [25]:
# Reshape an array
a2= np.array([1,2,3])
reshaped2=np.reshape(a2,(3,1))
reshaped2

array([[1],
       [2],
       [3]])

In [28]:
# Flatten an array
f1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened=np.ravel(f1) # Flatten to 1D array
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Transpose an array
e1=np.array([[1,2],[3,4],[5,6]])
transposed=np.transpose(e1) # Transpose the array : Rows become columns and vice versa.
transposed

array([[1, 3, 5],
       [2, 4, 6]])

In [33]:
# Stack arrays vertically
a1=np.array([1,2])
a2=np.array([3,4])
stacked=np.vstack([a1,a2]) # Stack a and b vertically
stacked

array([[1, 2],
       [3, 4]])

In [34]:
# Stack arrays horizontally
h1=np.array([1,2])
h2=np.array([3,4])
horizontal=np.hstack([h1,h2]) # Stack a and b horizontally
horizontal

array([1, 2, 3, 4])

In [35]:
# 3. Mathematical Functions