<a href="https://colab.research.google.com/github/Megha77/Expertise-fullstack-GenAI-Agentic-AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Array Creation Functions

In [2]:
import numpy as np

In [3]:
# Create an array from a list
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# Create an array with evenly spaced values
b=np.arange(0,10,3)
b

array([0, 3, 6, 9])

In [11]:
# Create an array filled with zeros
c=np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Create an array filled with zeros
d=np.zeros((2,3),dtype=int)
#d=np.zeros((2,4),dtype=int)
d

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
# Create an array filled with ones
e=np.ones((3,4))
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# Create an identity matrix
f=np.eye(4) # 4x4 identity matrix
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])